language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install: 
  - pip install .
  - pip install -r requirements.txt
  # - pip install -r requirements.pip
# command to run tests
script: py.test
# script: coverage run manage.py test